---
- name: localhost
  hosts: 127.0.0.1
  connection: local
  vars:
    docker:
      image_name: tutum/hello-world
      instance_name: another-http-hello-world
      port: 80
      map_to_port: 50002
  become: yes
  tasks:
  - import_role:
      name: app
