spring:
  profiles:
    active: dev

security:
  basic:
    enabled: false
  ignored: /**

management:
  security:
    enabled: false

server:
  port: 9090

---

spring:
  profiles: dev
datasource:
  driver: org.h2.Driver
  url: jdbc:h2:mem:devopsdb
  username: sa
  password:

---

spring:
  profiles: prod



