spring:
  profiles:
    active: dev

security:
  basic:
    enabled: false
  ignored: /**

management:
  security:
    enabled: false

server:
  port: 9090

---

spring:
  profiles: dev
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true
datasource:
  driver: org.h2.Driver
  url: jdbc:h2:mem:devopsdb
  username: sa
  password:

---

spring:
  profiles: prod
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace